import removeDuplicateFunction from 'functions/removeDublicateFunction';
//
const data = {
  sku_department: [
    'SURGICAL',
    'HEALTH CARE PRODUCTS',
    'CONFECTIONARY',
    'MEDICINES',
    'CONSUMER',
    'COMPOUNDING',
    'Medicines',
    'SURGICAL',
    'HEALTH CARE PRODUCTS',
    'MEDICINES',
    'CONFECTIONARY',
    'CONSUMER',
    'Mens Health',
    'NON-PHARMA',
    'IMPORTED',
  ],
  item_nature: ['Refrigerator', 'Room Temperature', 'Narcotics'],
  tax_code: ['GST 15%', 'GST 17%', 'GST 5%', 'GST 22%', 'Advance WHT'],
  purchasing_unit: ['Carton'],
  selling_unit: [['Carton'], ['Box', 'Pieces'], ['Pieces', 'Strips']],
  item_release_level: ['POS', 'ECOM', 'Both'],
  price_levels: ['Special Sale', 'Promotion'],
  stock_nature: ['Stock', 'Non Stock', 'Internal Consumption'],
  bar_code: ['QR Code', '2D Code', '1D Code'],
  item_storage_location: ['Aisle', 'Racks', 'Shelf Level'],
  item_tracking_level: ['Batch', 'Expiry'],
  sales_tax_group: [
    '0% GST',
    '1% GST',
    '4% GST',
    '5% GST',
    '17% GST',
    '18% GST',
    '19% GST',
    '20% GST',
    '21% GST',
    '22% GST',
  ],
};
//
export const ProductDropDownData = {
  sku_department: removeDuplicateFunction(data.sku_department),
  item_nature: removeDuplicateFunction(data.item_nature),
  tax_code: removeDuplicateFunction(data.tax_code),
  purchasing_unit: removeDuplicateFunction(data.purchasing_unit),
  selling_unit: removeDuplicateFunction(data.selling_unit),
  item_release_level: removeDuplicateFunction(data.item_release_level),
  price_levels: removeDuplicateFunction(data.price_levels),
  stock_nature: removeDuplicateFunction(data.stock_nature),
  bar_code: removeDuplicateFunction(data.bar_code),
  item_storage_location: removeDuplicateFunction(data.item_storage_location),
  item_tracking_level: removeDuplicateFunction(data.item_tracking_level),
  sales_tax_group: removeDuplicateFunction(data.sales_tax_group),
};
